// SathyaMithra — Full Scheme Catalog
// Source: myscheme.gov.in (real government schemes)

export interface Scheme {
  id: string;
  name: string;
  ministry: string;
  category: string;
  state: string; // 'Central' or state name
  benefit: string;
  benefitAmount?: string;
  description: string;
  eligibility: string[];
  documents: string[];
  applicationUrl: string;
  tags: string[];
  featured?: boolean;
}

export const CATEGORIES = [
  { id: 'agriculture', label: 'Agriculture, Rural & Environment', icon: '🌾', color: 'green' },
  { id: 'banking', label: 'Banking, Financial Services & Insurance', icon: '🏦', color: 'blue' },
  { id: 'business', label: 'Business & Entrepreneurship', icon: '💼', color: 'purple' },
  { id: 'education', label: 'Education & Learning', icon: '🎓', color: 'indigo' },
  { id: 'health', label: 'Health & Wellness', icon: '🏥', color: 'red' },
  { id: 'housing', label: 'Housing & Shelter', icon: '🏠', color: 'orange' },
  { id: 'law', label: 'Public Safety, Law & Justice', icon: '⚖️', color: 'slate' },
  { id: 'science', label: 'Science, IT & Communications', icon: '💻', color: 'cyan' },
  { id: 'skills', label: 'Skills & Employment', icon: '🔧', color: 'yellow' },
  { id: 'social', label: 'Social Welfare & Empowerment', icon: '🤝', color: 'pink' },
  { id: 'sports', label: 'Sports & Culture', icon: '🏆', color: 'amber' },
  { id: 'transport', label: 'Transport & Infrastructure', icon: '🚌', color: 'stone' },
  { id: 'tourism', label: 'Travel & Tourism', icon: '✈️', color: 'teal' },
  { id: 'utility', label: 'Utility & Sanitation', icon: '💧', color: 'sky' },
  { id: 'women', label: 'Women & Child', icon: '👩👧', color: 'rose' },
];

export const STATES = [
  'Central Government',
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Andaman & Nicobar Islands', 'Chandigarh', 'Dadra & Nagar Haveli', 'Daman & Diu',
  'Delhi', 'Jammu & Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry',
];

export const ALL_SCHEMES: Scheme[] = [
  // ── AGRICULTURE ──
  {
    id: 'pm-kisan',
    name: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'agriculture',
    state: 'Central Government',
    benefit: 'Direct income support',
    benefitAmount: '₹6,000/year',
    description: 'Income support of ₹6,000 per year to all landholding farmer families across the country in three equal instalments of ₹2,000 each.',
    eligibility: ['Landholding farmer family', 'Must have cultivable land', 'Not a government employee', 'Income tax payer families excluded'],
    documents: ['Aadhaar Card', 'Land Records (Khatauni)', 'Bank Account details', 'Mobile number'],
    applicationUrl: 'https://pmkisan.gov.in',
    tags: ['farmer', 'income support', 'direct benefit'],
    featured: true,
  },
  {
    id: 'pm-fasal-bima',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'agriculture',
    state: 'Central Government',
    benefit: 'Crop insurance coverage',
    benefitAmount: 'Up to full sum insured',
    description: 'Financial support to farmers suffering crop loss/damage due to unforeseen events like natural calamities, pests and diseases.',
    eligibility: ['All farmers growing notified crops', 'Loanee farmers compulsory', 'Non-loanee farmers voluntary'],
    documents: ['Aadhaar Card', 'Land records', 'Bank passbook', 'Sowing certificate'],
    applicationUrl: 'https://pmfby.gov.in',
    tags: ['crop insurance', 'natural disaster', 'farmer'],
    featured: true,
  },
  {
    id: 'kisan-credit-card',
    name: 'Kisan Credit Card (KCC)',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'agriculture',
    state: 'Central Government',
    benefit: 'Short-term credit for farming needs',
    benefitAmount: 'Up to ₹3 lakh at 4% interest',
    description: 'Adequate and timely credit support from banking system to farmers for their cultivation and allied activities.',
    eligibility: ['All farmers (owner cultivators, tenant farmers, SHGs)', 'Age 18-75 years'],
    documents: ['Aadhaar Card', 'Land records', 'Passport photo', 'Income certificate'],
    applicationUrl: 'https://www.nabard.org',
    tags: ['credit', 'loan', 'farmer', 'bank'],
  },
  {
    id: 'soil-health-card',
    name: 'Soil Health Card Scheme',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'agriculture',
    state: 'Central Government',
    benefit: 'Free soil health card & fertiliser advice',
    description: 'Soil health cards carrying crop-wise recommendations of nutrients/fertilizers required for individual farms.',
    eligibility: ['All farmers with agricultural land'],
    documents: ['Aadhaar Card', 'Land records'],
    applicationUrl: 'https://soilhealth.dac.gov.in',
    tags: ['soil', 'fertilizer', 'farmer'],
  },
  {
    id: 'pm-krishi-sinchayee',
    name: 'Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)',
    ministry: 'Ministry of Jal Shakti',
    category: 'agriculture',
    state: 'Central Government',
    benefit: 'Irrigation infrastructure & water efficiency',
    description: 'Expand cultivable area under assurance of irrigation, improve water use efficiency to reduce wastage and enhance recharge of aquifers.',
    eligibility: ['Farmers with landholding', 'FPOs and cooperatives eligible'],
    documents: ['Aadhaar Card', 'Land records', 'Bank passbook'],
    applicationUrl: 'https://pmksy.gov.in',
    tags: ['irrigation', 'water', 'farmer'],
  },
  {
    id: 'mgnregs',
    name: 'MGNREGS (Mahatma Gandhi National Rural Employment Guarantee)',
    ministry: 'Ministry of Rural Development',
    category: 'agriculture',
    state: 'Central Government',
    benefit: '100 days guaranteed employment',
    benefitAmount: 'Wage rate ₹237-₹374/day (state-wise)',
    description: 'Guarantees right to work — 100 days of wage employment per year to every rural household whose adult members volunteer to do unskilled manual work.',
    eligibility: ['Rural household adult members', 'Willing to do unskilled manual work'],
    documents: ['Job Card (issued by Gram Panchayat)', 'Aadhaar Card', 'Bank passbook'],
    applicationUrl: 'https://nrega.nic.in',
    tags: ['employment', 'rural', 'wage', 'job card'],
    featured: true,
  },
  {
    id: 'pm-kusum',
    name: 'PM-KUSUM (Kisan Urja Suraksha evam Utthaan Mahabhiyan)',
    ministry: 'Ministry of New and Renewable Energy',
    category: 'agriculture',
    state: 'Central Government',
    benefit: 'Solar pump & solar power for irrigation',
    benefitAmount: 'Subsidy up to 60%',
    description: 'Installation of solar pumps and grid-connected solar power plants for farmers to boost income and ensure energy security in the farm sector.',
    eligibility: ['Farmers with irrigated land', 'Farmer groups / FPOs / cooperatives'],
    documents: ['Aadhaar Card', 'Land records', 'Bank passbook'],
    applicationUrl: 'https://mnre.gov.in/solar/schemes',
    tags: ['solar', 'energy', 'irrigation', 'farmer'],
  },

  // ── BANKING & INSURANCE ──
  {
    id: 'pm-jjby',
    name: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
    ministry: 'Ministry of Finance',
    category: 'banking',
    state: 'Central Government',
    benefit: 'Life insurance cover',
    benefitAmount: '₹2 lakh on death',
    description: 'Term life insurance policy offering coverage of ₹2 lakh for death due to any reason at an annual premium of only ₹436.',
    eligibility: ['Age 18-50 years', 'Bank account holder', 'Savings account required'],
    documents: ['Aadhaar Card', 'Bank passbook', 'Mobile number'],
    applicationUrl: 'https://jansuraksha.gov.in',
    tags: ['life insurance', 'term plan', 'affordable'],
    featured: true,
  },
  {
    id: 'pmsby',
    name: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
    ministry: 'Ministry of Finance',
    category: 'banking',
    state: 'Central Government',
    benefit: 'Accident insurance',
    benefitAmount: '₹2 lakh accidental death, ₹1 lakh partial disability',
    description: 'Accidental death and disability insurance scheme for savings bank account holders aged 18 to 70 years at ₹20 per annum.',
    eligibility: ['Age 18-70 years', 'Savings bank account holder'],
    documents: ['Aadhaar Card', 'Bank passbook'],
    applicationUrl: 'https://jansuraksha.gov.in',
    tags: ['accident insurance', 'disability', 'affordable'],
    featured: true,
  },
  {
    id: 'atal-pension',
    name: 'Atal Pension Yojana (APY)',
    ministry: 'Ministry of Finance / PFRDA',
    category: 'banking',
    state: 'Central Government',
    benefit: 'Guaranteed pension after age 60',
    benefitAmount: '₹1,000–₹5,000/month pension',
    description: 'Subscribers will receive minimum guaranteed pension of ₹1,000–₹5,000 per month from age 60, depending on their contributions.',
    eligibility: ['Age 18-40 years', 'Bank / post office account holder', 'Not an income tax payer (earlier)'],
    documents: ['Aadhaar Card', 'Bank passbook', 'Mobile number'],
    applicationUrl: 'https://npscra.nsdl.co.in',
    tags: ['pension', 'retirement', 'savings'],
  },
  {
    id: 'jan-dhan',
    name: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    ministry: 'Ministry of Finance',
    category: 'banking',
    state: 'Central Government',
    benefit: 'Zero-balance bank account with benefits',
    benefitAmount: '₹2 lakh accident cover + ₹10,000 overdraft',
    description: 'Financial inclusion scheme ensuring access to financial services — savings accounts, remittance, credit, insurance, pension.',
    eligibility: ['Any Indian citizen without bank account', 'No minimum balance required'],
    documents: ['Aadhaar Card or any KYC document'],
    applicationUrl: 'https://pmjdy.gov.in',
    tags: ['bank account', 'financial inclusion', 'zero balance'],
    featured: true,
  },

  // ── BUSINESS & ENTREPRENEURSHIP ──
  {
    id: 'mudra-yojana',
    name: 'PM Mudra Yojana (PMMY)',
    ministry: 'Ministry of Finance',
    category: 'business',
    state: 'Central Government',
    benefit: 'Collateral-free loans for micro enterprises',
    benefitAmount: 'Up to ₹10 lakh',
    description: 'Provides loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises under Shishu (₹50k), Kishore (₹5L), Tarun (₹10L) categories.',
    eligibility: ['Non-farm income generating activities', 'Manufacturing, trading or service sector', 'No collateral required'],
    documents: ['Aadhaar Card', 'PAN Card', 'Business plan', 'Bank statement'],
    applicationUrl: 'https://mudra.org.in',
    tags: ['loan', 'micro enterprise', 'collateral-free', 'self employment'],
    featured: true,
  },
  {
    id: 'pmegp',
    name: 'PMEGP (PM Employment Generation Programme)',
    ministry: 'Ministry of MSME',
    category: 'business',
    state: 'Central Government',
    benefit: 'Subsidy on project cost for new enterprises',
    benefitAmount: '15–35% subsidy on project cost',
    description: 'Credit-linked subsidy programme to generate employment opportunities in rural and urban areas through setting up new self-employment ventures.',
    eligibility: ['Age 18+', 'Minimum 8th pass for projects above ₹10L', 'No income ceiling'],
    documents: ['Aadhaar Card', 'PAN Card', 'Educational certificate', 'Project report'],
    applicationUrl: 'https://kviconline.gov.in/pmegpeportal',
    tags: ['subsidy', 'employment', 'manufacturing', 'rural'],
  },
  {
    id: 'startup-india-seed',
    name: 'Startup India Seed Fund Scheme',
    ministry: 'Ministry of Commerce & Industry (DPIIT)',
    category: 'business',
    state: 'Central Government',
    benefit: 'Seed funding for early-stage startups',
    benefitAmount: 'Up to ₹5 crore per incubator',
    description: 'Financial assistance to startups for proof of concept, prototype development, product trials, market entry and commercialization.',
    eligibility: ['DPIIT recognized startup', 'Not received more than ₹10L from other schemes', 'Incorporated less than 2 years ago'],
    documents: ['DPIIT recognition certificate', 'Incorporation certificate', 'Business plan', 'Financial statements'],
    applicationUrl: 'https://seedfund.startupindia.gov.in',
    tags: ['startup', 'seed fund', 'incubator', 'innovation'],
  },
  {
    id: 'stand-up-india',
    name: 'Stand-Up India',
    ministry: 'Ministry of Finance / SIDBI',
    category: 'business',
    state: 'Central Government',
    benefit: 'Bank loans for SC/ST and women entrepreneurs',
    benefitAmount: '₹10 lakh to ₹1 crore',
    description: 'Facilitates bank loans for SC, ST and women beneficiaries to set up greenfield enterprises in manufacturing, services or trading sector.',
    eligibility: ['SC/ST or women entrepreneur', 'Greenfield enterprise', 'Age 18+'],
    documents: ['Aadhaar Card', 'Caste certificate (SC/ST)', 'Business plan', 'Bank statement'],
    applicationUrl: 'https://standupindia.in',
    tags: ['SC/ST', 'women entrepreneur', 'loan', 'greenfield'],
  },
  {
    id: 'svanidhi',
    name: 'PM SVANidhi (Street Vendor Atmanirbhar Nidhi)',
    ministry: 'Ministry of Housing & Urban Affairs',
    category: 'business',
    state: 'Central Government',
    benefit: 'Working capital loan for street vendors',
    benefitAmount: '₹10,000 → ₹20,000 → ₹50,000',
    description: 'Collateral-free working capital loans to street vendors to resume livelihoods affected by COVID-19 pandemic.',
    eligibility: ['Urban street vendor', 'Vending in cities/towns', 'Certificate of vending / letter of recommendation'],
    documents: ['Aadhaar Card', 'Vendor ID', 'Mobile number'],
    applicationUrl: 'https://pmsvanidhi.mohua.gov.in',
    tags: ['street vendor', 'working capital', 'urban', 'loan'],
    featured: true,
  },

  // ── EDUCATION ──
  {
    id: 'nsp-scholarship',
    name: 'National Scholarship Portal (NSP)',
    ministry: 'Ministry of Electronics & IT',
    category: 'education',
    state: 'Central Government',
    benefit: 'Various central & state scholarships',
    benefitAmount: '₹1,000–₹25,000/year',
    description: 'Single-window electronic platform for various scholarships for students from pre-matric to post-doctoral levels.',
    eligibility: ['Indian student', 'Varies by scheme — merit, income, category'],
    documents: ['Aadhaar Card', 'Income certificate', 'Mark sheets', 'Bank passbook', 'Caste certificate'],
    applicationUrl: 'https://scholarships.gov.in',
    tags: ['scholarship', 'student', 'education', 'merit'],
    featured: true,
  },
  {
    id: 'pm-vidya-lakshmi',
    name: 'PM Vidya Lakshmi (Education Loan)',
    ministry: 'Ministry of Education / Ministry of Finance',
    category: 'education',
    state: 'Central Government',
    benefit: 'Education loan at subsidised interest',
    benefitAmount: 'Up to ₹7.5 lakh without collateral',
    description: 'Single window portal for students to access information and make applications for educational loans from banks.',
    eligibility: ['Indian student', 'Admission in recognized institution', 'Family income criteria applies'],
    documents: ['Aadhaar Card', 'Admission letter', 'Fee structure', 'Income certificate'],
    applicationUrl: 'https://www.vidyalakshmi.co.in',
    tags: ['education loan', 'higher education', 'student', 'bank'],
  },
  {
    id: 'mid-day-meal',
    name: 'PM POSHAN (Mid-Day Meal Scheme)',
    ministry: 'Ministry of Education',
    category: 'education',
    state: 'Central Government',
    benefit: 'Free mid-day meal for school children',
    description: 'Nutritional support to children studying in government and government-aided schools across the country.',
    eligibility: ['Students of Class I-VIII in government schools', 'Children in madrasas supported by govt'],
    documents: ['School enrollment proof'],
    applicationUrl: 'https://pmposhan.education.gov.in',
    tags: ['nutrition', 'school', 'free meal', 'children'],
  },
  {
    id: 'samagra-shiksha',
    name: 'Samagra Shiksha Abhiyan',
    ministry: 'Ministry of Education',
    category: 'education',
    state: 'Central Government',
    benefit: 'Holistic school education support',
    description: 'Integrated scheme covering pre-school to Class XII for holistic education — covering infrastructure, quality, teachers training.',
    eligibility: ['Students in government schools'],
    documents: ['School enrollment', 'Aadhaar Card'],
    applicationUrl: 'https://samagrashiksha.in',
    tags: ['school education', 'quality', 'infrastructure'],
  },
  {
    id: 'free-coaching-sc-st',
    name: 'Free Coaching Scheme for SC/ST Students',
    ministry: 'Ministry of Social Justice & Empowerment',
    category: 'education',
    state: 'Central Government',
    benefit: 'Free coaching for competitive exams',
    description: 'Free coaching for SC and ST students for Group A&B examinations conducted by UPSC, SSC, PSCs, and other competitive exams.',
    eligibility: ['SC/ST student', 'Family income below ₹8 lakh/year', 'Age limit as per exam'],
    documents: ['Aadhaar Card', 'Caste certificate', 'Income certificate', 'Educational certificates'],
    applicationUrl: 'https://socialjustice.nic.in',
    tags: ['SC/ST', 'coaching', 'competitive exam', 'UPSC'],
  },
  {
    id: 'anganwadi-icds',
    name: 'Anganwadi Services (ICDS)',
    ministry: 'Ministry of Women & Child Development',
    category: 'education',
    state: 'Central Government',
    benefit: 'Early childhood care & pre-school education',
    description: 'Integrated Child Development Services providing nutrition, health check-ups, immunization, pre-school education for children 0-6 years.',
    eligibility: ['Children 0-6 years', 'Pregnant women', 'Lactating mothers'],
    documents: ['Birth certificate', 'Aadhaar Card (mother)'],
    applicationUrl: 'https://wcd.nic.in/schemes',
    tags: ['child', 'preschool', 'nutrition', 'anganwadi'],
  },

  // ── HEALTH ──
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat PM-JAY',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'health',
    state: 'Central Government',
    benefit: 'Cashless health insurance',
    benefitAmount: '₹5 lakh/year per family',
    description: 'World\'s largest health assurance scheme providing cover of ₹5 lakh per family per year for secondary and tertiary hospitalization.',
    eligibility: ['Families in SECC database', 'BPL families', 'Deprived rural households'],
    documents: ['Aadhaar Card', 'Ration card', 'SECC letter'],
    applicationUrl: 'https://pmjay.gov.in',
    tags: ['health insurance', 'cashless', 'hospitalization', 'BPL'],
    featured: true,
  },
  {
    id: 'pm-surakshit-matritva',
    name: 'Pradhan Mantri Surakshit Matritva Abhiyan',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'health',
    state: 'Central Government',
    benefit: 'Free antenatal check-ups on 9th of every month',
    description: 'Provides assured comprehensive and quality ANC to pregnant women on the 9th of every month at government health facilities.',
    eligibility: ['Pregnant women in 2nd/3rd trimester'],
    documents: ['Aadhaar Card', 'MCP card'],
    applicationUrl: 'https://pmsma.nhp.gov.in',
    tags: ['maternal health', 'pregnancy', 'antenatal', 'free checkup'],
  },
  {
    id: 'janani-suraksha',
    name: 'Janani Suraksha Yojana (JSY)',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'health',
    state: 'Central Government',
    benefit: 'Cash assistance for institutional delivery',
    benefitAmount: '₹1,400 (rural) / ₹1,000 (urban)',
    description: 'Safe motherhood intervention under NHM promoting institutional delivery among poor pregnant women to reduce maternal and neonatal mortality.',
    eligibility: ['Below poverty line pregnant women', 'Age 19 or above', 'Up to 2 live births'],
    documents: ['Aadhaar Card', 'BPL card', 'MCP card'],
    applicationUrl: 'https://nhm.gov.in/index1.php?lang=1&level=3&sublinkid=841&lid=309',
    tags: ['maternity', 'delivery', 'cash benefit', 'BPL'],
  },
  {
    id: 'rashtriya-swasthya-bima',
    name: 'Rashtriya Swasthya Bima Yojana (RSBY)',
    ministry: 'Ministry of Labour & Employment',
    category: 'health',
    state: 'Central Government',
    benefit: 'Health insurance for unorganized workers',
    benefitAmount: '₹30,000/year per family',
    description: 'Health insurance scheme for workers in unorganised sector and their families.',
    eligibility: ['BPL unorganized sector worker', 'Family of up to 5 members'],
    documents: ['Aadhaar Card', 'BPL certificate', 'Smart card'],
    applicationUrl: 'https://rsby.gov.in',
    tags: ['unorganized worker', 'health insurance', 'BPL'],
  },
  {
    id: 'national-mental-health',
    name: 'National Mental Health Programme',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'health',
    state: 'Central Government',
    benefit: 'Free mental health services',
    description: 'Provides accessible, affordable quality mental health care to all sections of society.',
    eligibility: ['Any Indian citizen'],
    documents: ['Aadhaar Card'],
    applicationUrl: 'https://nmhp.nhp.gov.in',
    tags: ['mental health', 'free treatment', 'psychiatry'],
  },

  // ── HOUSING ──
  {
    id: 'pmay-gramin',
    name: 'PM Awas Yojana – Gramin (PMAY-G)',
    ministry: 'Ministry of Rural Development',
    category: 'housing',
    state: 'Central Government',
    benefit: 'Financial assistance for rural house construction',
    benefitAmount: '₹1.2 lakh (plain) / ₹1.3 lakh (hilly/north-east)',
    description: 'Provides financial assistance to BPL rural households for construction of pucca house with basic amenities.',
    eligibility: ['Rural household', 'No pucca house', 'SECC-2011 listed', 'Not availed housing benefit earlier'],
    documents: ['Aadhaar Card', 'SECC beneficiary letter', 'Bank passbook', 'Land certificate'],
    applicationUrl: 'https://pmayg.nic.in',
    tags: ['housing', 'rural', 'pucca house', 'BPL'],
    featured: true,
  },
  {
    id: 'pmay-urban',
    name: 'PM Awas Yojana – Urban (PMAY-U)',
    ministry: 'Ministry of Housing & Urban Affairs',
    category: 'housing',
    state: 'Central Government',
    benefit: 'Subsidy on home loan interest',
    benefitAmount: 'Interest subsidy up to ₹2.67 lakh',
    description: 'Provides affordable housing to urban poor including slum dwellers through credit linked subsidy and in-situ slum redevelopment.',
    eligibility: ['Annual income up to ₹18 lakh', 'No pucca house', 'First-time home buyer'],
    documents: ['Aadhaar Card', 'Income certificate', 'Property documents', 'Bank statement'],
    applicationUrl: 'https://pmaymis.gov.in',
    tags: ['housing', 'urban', 'home loan', 'subsidy', 'EWS/LIG'],
    featured: true,
  },
  {
    id: 'indira-awas',
    name: 'Indira Gandhi Awas Yojana (Now PMAY-G)',
    ministry: 'Ministry of Rural Development',
    category: 'housing',
    state: 'Central Government',
    benefit: 'Rural housing construction support',
    description: 'Scheme for providing shelter to the houseless and those living in kutcha/dilapidated houses in rural areas.',
    eligibility: ['BPL rural household', 'SC/ST/OBC/minorities/ex-servicemen/disabled'],
    documents: ['Aadhaar Card', 'BPL card', 'Land records'],
    applicationUrl: 'https://pmayg.nic.in',
    tags: ['rural housing', 'BPL', 'shelter'],
  },

  // ── SKILLS & EMPLOYMENT ──
  {
    id: 'pmkvy',
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
    ministry: 'Ministry of Skill Development & Entrepreneurship',
    category: 'skills',
    state: 'Central Government',
    benefit: 'Free skill training + certification + stipend',
    benefitAmount: 'Free training, monetary reward on passing',
    description: 'Skill certification scheme to enable large number of Indian youth to take up industry-relevant skill training and earn a better livelihood.',
    eligibility: ['Indian citizen', 'Age 15-45 years', 'School/college dropout or unemployed'],
    documents: ['Aadhaar Card', 'Educational certificate', 'Bank passbook'],
    applicationUrl: 'https://www.pmkvyofficial.org',
    tags: ['skill training', 'certificate', 'employment', 'youth'],
    featured: true,
  },
  {
    id: 'naps',
    name: 'National Apprenticeship Promotion Scheme (NAPS)',
    ministry: 'Ministry of Skill Development & Entrepreneurship',
    category: 'skills',
    state: 'Central Government',
    benefit: 'Stipend support for apprentices',
    benefitAmount: 'Up to ₹1,500/month Government contribution',
    description: 'Promotes apprenticeship in industry by sharing 25% of prescribed stipend (max ₹1,500/month) with employers.',
    eligibility: ['Passed Class 5 and above', 'Age 14+'],
    documents: ['Aadhaar Card', 'Educational certificates', 'Date of birth proof'],
    applicationUrl: 'https://apprenticeshipindia.org',
    tags: ['apprenticeship', 'stipend', 'on-the-job training', 'industry'],
  },
  {
    id: 'deen-dayal-upadhyaya',
    name: 'Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)',
    ministry: 'Ministry of Rural Development',
    category: 'skills',
    state: 'Central Government',
    benefit: 'Free skill training for rural youth',
    benefitAmount: 'Free training + placement assistance',
    description: 'Part of the National Rural Livelihood Mission, DDU-GKY funds skill training projects to give rural youth access to wage employment.',
    eligibility: ['Rural youth', 'Age 15-35 years', 'Poor rural household'],
    documents: ['Aadhaar Card', 'Ration card', 'Educational certificate', 'Income certificate'],
    applicationUrl: 'https://ddugky.gov.in',
    tags: ['rural youth', 'skill', 'placement', 'employment'],
  },

  // ── SOCIAL WELFARE ──
  {
    id: 'nsap-pension',
    name: 'National Social Assistance Programme (NSAP)',
    ministry: 'Ministry of Rural Development',
    category: 'social',
    state: 'Central Government',
    benefit: 'Monthly pension for elderly, widows, disabled',
    benefitAmount: '₹200–₹500/month (Central) + State top-up',
    description: 'Social assistance for poor households — old age pension (IGNOAPS), widow pension (IGNWPS), disability pension (IGNDPS), family benefit (NFBS).',
    eligibility: ['BPL household', 'Age 60+ (old age)', 'Widows 40-79 years', 'Disabled persons'],
    documents: ['Aadhaar Card', 'BPL card', 'Age proof', 'Disability certificate (if applicable)'],
    applicationUrl: 'https://nsap.nic.in',
    tags: ['pension', 'elderly', 'widow', 'disability', 'BPL'],
    featured: true,
  },
  {
    id: 'pm-ujjwala',
    name: 'Pradhan Mantri Ujjwala Yojana (PMUY)',
    ministry: 'Ministry of Petroleum & Natural Gas',
    category: 'social',
    state: 'Central Government',
    benefit: 'Free LPG connection for BPL women',
    benefitAmount: 'Free gas connection + first refill subsidy',
    description: 'Provides free LPG connections to women belonging to BPL households to protect health of women and children from indoor pollution.',
    eligibility: ['BPL woman', 'Not have LPG connection in household', 'Ration card / BPL list'],
    documents: ['Aadhaar Card', 'BPL ration card', 'Bank passbook', 'Passport photo'],
    applicationUrl: 'https://pmuy.gov.in',
    tags: ['LPG', 'BPL', 'women', 'clean cooking fuel'],
    featured: true,
  },
  {
    id: 'national-food-security',
    name: 'National Food Security Act (NFSA) / PDS',
    ministry: 'Ministry of Consumer Affairs, Food & PDS',
    category: 'social',
    state: 'Central Government',
    benefit: 'Subsidized food grains',
    benefitAmount: '5 kg grain/person/month at ₹1–₹3/kg',
    description: 'Entitles 75% rural and 50% urban population to receive subsidised food grains (rice, wheat, coarse grains) through Public Distribution System.',
    eligibility: ['Priority households', 'Antyodaya Anna Yojana (AAY) households'],
    documents: ['Ration card'],
    applicationUrl: 'https://nfsa.gov.in',
    tags: ['food', 'ration', 'PDS', 'subsidy', 'BPL'],
    featured: true,
  },
  {
    id: 'pm-aawas-jan-andolan',
    name: 'Pradhan Mantri Garib Kalyan Anna Yojana',
    ministry: 'Ministry of Consumer Affairs, Food & PDS',
    category: 'social',
    state: 'Central Government',
    benefit: 'Free food grains to beneficiaries',
    benefitAmount: '5 kg free rice/wheat per person per month',
    description: 'Free food grains to all NFSA beneficiaries merged with regular PDS entitlements from 2024.',
    eligibility: ['NFSA ration card holders'],
    documents: ['Ration card', 'Aadhaar Card'],
    applicationUrl: 'https://nfsa.gov.in',
    tags: ['free food', 'ration', 'poor', 'pandemic relief'],
  },
  {
    id: 'sukanya-samridhi',
    name: 'Sukanya Samridhi Yojana (SSY)',
    ministry: 'Ministry of Finance',
    category: 'social',
    state: 'Central Government',
    benefit: 'High-interest savings scheme for girl child',
    benefitAmount: '8.2% p.a. interest (tax-free)',
    description: 'Small savings scheme for girl children encouraging parents to build a fund for the future education and marriage expenses of their girl child.',
    eligibility: ['Girl child up to 10 years of age', 'Indian resident'],
    documents: ['Girl child birth certificate', 'Parent Aadhaar Card', 'Address proof'],
    applicationUrl: 'https://www.indiapost.gov.in',
    tags: ['girl child', 'savings', 'education', 'marriage'],
    featured: true,
  },

  // ── WOMEN & CHILD ──
  {
    id: 'beti-bachao-beti-padhao',
    name: 'Beti Bachao Beti Padhao',
    ministry: 'Ministry of Women & Child Development',
    category: 'women',
    state: 'Central Government',
    benefit: 'Awareness + education support for girls',
    description: 'Campaign addressing declining Child Sex Ratio and promoting girls\' education, welfare and empowerment.',
    eligibility: ['Girl children', 'Parents of girl child'],
    documents: ['Birth certificate', 'Aadhaar Card'],
    applicationUrl: 'https://wcd.nic.in/bbbp-schemes',
    tags: ['girl child', 'education', 'gender equality'],
  },
  {
    id: 'pradhan-mantri-matru-vandana',
    name: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
    ministry: 'Ministry of Women & Child Development',
    category: 'women',
    state: 'Central Government',
    benefit: 'Maternity benefit for first child',
    benefitAmount: '₹5,000 in 3 instalments',
    description: 'Partially compensates for wage loss during pregnancy and childcare to facilitate adequate rest and nutrition for pregnant and lactating mothers.',
    eligibility: ['Pregnant women for first live birth', 'Age 19+', 'Not central/state govt employee'],
    documents: ['Aadhaar Card', 'MCP card', 'Bank passbook', 'Mobile number'],
    applicationUrl: 'https://pmmvy.wcd.gov.in',
    tags: ['maternity benefit', 'pregnancy', 'cash benefit', 'women'],
    featured: true,
  },
  {
    id: 'one-stop-centre',
    name: 'One Stop Centre Scheme (Sakhi)',
    ministry: 'Ministry of Women & Child Development',
    category: 'women',
    state: 'Central Government',
    benefit: 'Integrated support for women in distress',
    description: 'Provides integrated support and assistance to women affected by violence including medical, legal, psychological, shelter and police assistance.',
    eligibility: ['Women affected by any form of violence'],
    documents: ['Any identity proof'],
    applicationUrl: 'https://wcd.nic.in/schemes/one-stop-centre-scheme',
    tags: ['women safety', 'violence', 'shelter', 'legal aid'],
  },
  {
    id: 'integrated-child-protection',
    name: 'Integrated Child Protection Scheme (ICPS)',
    ministry: 'Ministry of Women & Child Development',
    category: 'women',
    state: 'Central Government',
    benefit: 'Protection and rehabilitation for vulnerable children',
    description: 'Provides safe and secure environment for overall development of vulnerable and marginalized children.',
    eligibility: ['Children in difficult circumstances', 'Children in need of care and protection'],
    documents: ['Birth certificate', 'Aadhaar Card (if available)'],
    applicationUrl: 'https://wcd.nic.in',
    tags: ['child protection', 'rehabilitation', 'vulnerable children'],
  },

  // ── SPORTS & CULTURE ──
  {
    id: 'khelo-india',
    name: 'Khelo India Programme',
    ministry: 'Ministry of Youth Affairs & Sports',
    category: 'sports',
    state: 'Central Government',
    benefit: 'Annual scholarship for young athletes',
    benefitAmount: '₹6.4 lakh/year for 8 years',
    description: 'Revitalize sports culture in India at grassroots level through identifying and nurturing young talented athletes under age 18.',
    eligibility: ['Talented youth below 18 years', 'Excellence in identified sports'],
    documents: ['Aadhaar Card', 'Sports achievement certificates', 'Age proof', 'School certificate'],
    applicationUrl: 'https://kheloindia.gov.in',
    tags: ['sports', 'scholarship', 'youth', 'athlete'],
  },
  {
    id: 'target-olympic-podium',
    name: 'Target Olympic Podium Scheme (TOPS)',
    ministry: 'Ministry of Youth Affairs & Sports',
    category: 'sports',
    state: 'Central Government',
    benefit: 'Financial support for Olympic-level athletes',
    benefitAmount: 'Monthly allowance + training support',
    description: 'Identify and prepare potential medal prospects for Paris 2024 Olympics and beyond with customized training support.',
    eligibility: ['Elite athletes with Olympic potential', 'Selected by Sports Authority of India'],
    documents: ['Sports certificates', 'Aadhaar Card', 'Selection letter from SAI'],
    applicationUrl: 'https://sportsauthorityofindia.nic.in',
    tags: ['Olympics', 'elite athlete', 'training', 'medal'],
  },

  // ── UTILITY & SANITATION ──
  {
    id: 'swachh-bharat-gramin',
    name: 'Swachh Bharat Mission – Gramin (ODF)',
    ministry: 'Ministry of Jal Shakti',
    category: 'utility',
    state: 'Central Government',
    benefit: 'Financial assistance for household toilet construction',
    benefitAmount: '₹12,000 per household',
    description: 'Accelerate efforts to achieve universal sanitation coverage and improve cleanliness in rural India.',
    eligibility: ['Rural BPL household', 'No functional toilet at home'],
    documents: ['Aadhaar Card', 'BPL card', 'Bank passbook'],
    applicationUrl: 'https://sbm.gov.in',
    tags: ['sanitation', 'toilet', 'rural', 'ODF'],
  },
  {
    id: 'jal-jeevan-mission',
    name: 'Jal Jeevan Mission',
    ministry: 'Ministry of Jal Shakti',
    category: 'utility',
    state: 'Central Government',
    benefit: 'Piped drinking water to every rural household',
    description: 'Provide safe and adequate drinking water through individual household tap connections to all rural households by 2024.',
    eligibility: ['All rural households without tap water connection'],
    documents: ['Aadhaar Card', 'Residence proof'],
    applicationUrl: 'https://jaljeevanmission.gov.in',
    tags: ['drinking water', 'tap connection', 'rural', 'sanitation'],
  },
  {
    id: 'pm-sahaj-bijli',
    name: 'Saubhagya (PM Sahaj Bijli Har Ghar Yojana)',
    ministry: 'Ministry of Power',
    category: 'utility',
    state: 'Central Government',
    benefit: 'Free electricity connection for BPL households',
    description: 'Electricity connections to all un-electrified households in rural and urban areas.',
    eligibility: ['Un-electrified household', 'BPL households get free connection'],
    documents: ['Aadhaar Card', 'BPL card / ration card'],
    applicationUrl: 'https://saubhagya.gov.in',
    tags: ['electricity', 'connection', 'BPL', 'rural', 'urban'],
    featured: true,
  },

  // ── TRANSPORT ──
  {
    id: 'fastag',
    name: 'FASTag National Highway Toll',
    ministry: 'Ministry of Road Transport & Highways',
    category: 'transport',
    state: 'Central Government',
    benefit: 'Electronic toll payment — cashless, faster',
    description: 'RFID-based electronic toll collection system enabling seamless passage through toll plazas.',
    eligibility: ['All motor vehicle owners'],
    documents: ['Vehicle RC', 'Aadhaar Card', 'Passport photo'],
    applicationUrl: 'https://netc.npci.org.in',
    tags: ['toll', 'highway', 'cashless', 'vehicle'],
  },
  {
    id: 'pm-gram-sadak',
    name: 'Pradhan Mantri Gram Sadak Yojana (PMGSY)',
    ministry: 'Ministry of Rural Development',
    category: 'transport',
    state: 'Central Government',
    benefit: 'All-weather road connectivity to villages',
    description: 'Single-lane paved roads providing all-weather connectivity to unconnected rural habitations across India.',
    eligibility: ['Rural village without all-weather road access'],
    documents: ['Village panchayat resolution'],
    applicationUrl: 'https://pmgsy.nic.in',
    tags: ['roads', 'rural connectivity', 'village', 'infrastructure'],
  },

  // ── SCIENCE & IT ──
  {
    id: 'digital-india',
    name: 'Digital India Initiative',
    ministry: 'Ministry of Electronics & IT',
    category: 'science',
    state: 'Central Government',
    benefit: 'Digital services, literacy, connectivity',
    description: 'Transform India into a digitally empowered society and knowledge economy through digital infrastructure and digital services.',
    eligibility: ['All Indian citizens'],
    documents: ['Aadhaar Card'],
    applicationUrl: 'https://digitalindia.gov.in',
    tags: ['digital', 'IT', 'internet', 'e-services'],
  },
  {
    id: 'bharat-net',
    name: 'BharatNet (NOFN)',
    ministry: 'Ministry of Electronics & IT',
    category: 'science',
    state: 'Central Government',
    benefit: 'Broadband connectivity to gram panchayats',
    description: 'Provide broadband connectivity to all gram panchayats across India through optical fiber cable.',
    eligibility: ['Gram panchayat without broadband'],
    documents: ['NA — implemented at government level'],
    applicationUrl: 'https://bbnl.nic.in',
    tags: ['broadband', 'internet', 'village', 'connectivity'],
  },

  // ── TOURISM ──
  {
    id: 'swadesh-darshan',
    name: 'Swadesh Darshan Scheme',
    ministry: 'Ministry of Tourism',
    category: 'tourism',
    state: 'Central Government',
    benefit: 'Development of thematic tourist circuits',
    description: 'Integrated development of theme-based tourist circuits to promote tourism in India.',
    eligibility: ['State governments / ULBs can apply for funding'],
    documents: ['NA — state government scheme'],
    applicationUrl: 'https://tourism.gov.in',
    tags: ['tourism', 'travel', 'heritage', 'circuit'],
  },

  // ── LAW & JUSTICE ──
  {
    id: 'legal-aid-services',
    name: 'National Legal Services Authority (NALSA)',
    ministry: 'Department of Justice / NALSA',
    category: 'law',
    state: 'Central Government',
    benefit: 'Free legal aid and representation',
    description: 'Provides free legal aid to weaker sections of society to ensure no citizen is denied justice due to economic or other disabilities.',
    eligibility: ['SC/ST', 'Women', 'Children', 'Persons with disabilities', 'Victims of trafficking', 'BPL households'],
    documents: ['Aadhaar Card', 'Caste certificate (if SC/ST)', 'Income certificate'],
    applicationUrl: 'https://nalsa.gov.in',
    tags: ['legal aid', 'free lawyer', 'justice', 'court'],
  },
];

export function getSchemesByCategory(categoryId: string): Scheme[] {
  return ALL_SCHEMES.filter(s => s.category === categoryId);
}

export function getSchemesByState(state: string): Scheme[] {
  return ALL_SCHEMES.filter(s => s.state === state || state === 'Central Government');
}

export function getFeaturedSchemes(): Scheme[] {
  return ALL_SCHEMES.filter(s => s.featured);
}

export function searchSchemes(query: string): Scheme[] {
  const q = query.toLowerCase();
  return ALL_SCHEMES.filter(s =>
    s.name.toLowerCase().includes(q) ||
    s.description.toLowerCase().includes(q) ||
    s.tags.some(t => t.toLowerCase().includes(q)) ||
    s.ministry.toLowerCase().includes(q)
  );
}
